#### Login page
BBE_USERNAME = 'xpath://input[@id="emailAddress"]'
CONTINUE_BUTTON = 'xpath://button[text()="Continue"]'
BBE_PASSWORD = 'xpath://input[@id="password"]'
SIGN_BUTTON = 'xpath://button[text()="Sign In"]'
USERNAME_ERROR = '//div[contains(text(),"This field is required")]'
INVALID_USER_ERROR = '//div[contains(text(),"Invalid email address")]'
INCORRECT_EMAIL_ERROR = '//div[contains(text(),"Please enter correct email id")]'
PASSWORD_LENGTH_ERROR = '//div[contains(text(),"Password must")]'
INVALID_PASSWORD_ERROR = '//div[contains(text(),"Unable")]'
CUSTOMER = 'xpath://ul[@class="side-bar-icon"]/li[3]'
NAVIGATION_LIST = '//ul[@class="tabs"]/li'
PENDING_CHECKBOX = 'xpath://input[@id="pending"]//ancestor::div[1]'
FIRST_TABLE_DATA = '//div[@class="table-part"]/table/tbody//child::tr[1]'
BRAND_NAME = '//div[contains(@class,"brand-name")]'
PENDING_CONTRACT_CHECKBOX = 'xpath://input[contains(@id,"Pending Contract")]//ancestor::div[1]'
RECURRING_CHECK = '//label[text()="Recurring"]//parent::div'
RECURRING_SERVICE = '//tr[1]/td[4]/ul/li/div[contains(@class,"recurring-service")]'
SERVICE_AGREEMENT_HEADER = 'xpath://h3[contains(text(),"Service Agreement")]'
SERVICE_AGREEMENT_TAB = 'xpath://h4[contains(text(),"Service Agreement")]//parent::div'
SERVICE_AGREEMENT_ID = '//div[@id="agreement"]'
EDIT_CONTRACT_LOCATOR = 'xpath://button[text()="Edit Contract"]'
DSP_CHECK = '//label[text()="DSP Only"]//parent::div'
FIRST_BP = '//div[@class="company-name"]'
AGREEMENT_TAB = '//*[normalize-space(text())="Agreements"]'
ADD_AGREEMENT = '(//img[@alt="add"])[2]'
RECURRING_SERVICE_AGREEMENT = '//*[normalize-space(text())="Recurring Service Agreement"]'
CONTRACT_TYPE = '//label[text()="Contract Type"]'
CONTRACT_TYPE_FIELD = '//input[@name="contract_type"]'
CUSTOMER_NAME = '//label[text()="Contract Length"]//following::li/div/label[normalize-space(text())="Customer Name"]'
AGREEMENT_SECTION = '//div[@class="sidebar"]'
ONE_TIME_AGREEMENT = '//li[text()="One Time Agreements"]'
CUSTOMER_NAME_LOCATOR = 'xpath://input[contains(@name,"company_name")]'
FEE_STRUCTURE = '//h4[normalize-space(text())="Fee Structure"]'
ACCOUNT_TYPE = '//label[text()="Account Type"]//following::div[3]'
ACCOUNT_TYPE_VALUE = '//label[text()="Account Type"]//following::div[3]/div[contains(@class,"react-select__single-value")]'
SELLER_ACCOUNT_TYPE = '//*[normalize-space(text())="Seller"]'
VENDOR_ACCOUNT_TYPE = '//*[normalize-space(text())="Vendor"]'
HYBRID_ACCOUNT_TYPE = '//*[normalize-space(text())="Hybrid"]'
FEE_TYPE = '//label[@for="fee type"]'
FEE_TYPE_DROPDOWN = '(//label[@for="fee type"]//following::div[contains(@class,"react-select")])[1]'
SELLER_RETAINER_FIXED = '//div[contains(text(),"Seller")]//following::label[text()="Fixed"][1]'
SELLER_RETAINER_QUARTERLY = '//label[@for="seller_retainer_quarterly"]'
SELLER_RETAINER_FIRST = '(//input[contains(@id,"1st quarterly")])[1]'
SELLER_RETAINER_SECOND = '(//input[contains(@id,"2nd quarterly")])[1]'
SELLER_RETAINER_THIRD = '(//input[contains(@id,"3rd quarterly")])[1]'
SELLER_RETAINER_FOURTH = '(//input[contains(@id,"4th quarterly")])[1]'
SELLER_RETAINER_MONTHLY = '//label[@for="seller_retainer_monthly"]'
SELLER_RETAINER_JAN = '(//input[contains(@name,"january month")])[1]'
SELLER_RETAINER_FEB = '(//input[contains(@name,"february month")])[1]'
SELLER_RETAINER_MARCH = '(//input[contains(@name,"march month")])[1]'
SELLER_RETAINER_APRIL = '(//input[contains(@name,"april month")])[1]'
SELLER_RETAINER_MAY = '(//input[contains(@name,"may month")])[1]'
SELLER_RETAINER_JUNE = '(//input[contains(@name,"june month")])[1]'
SELLER_RETAINER_JULY = '(//input[contains(@name,"july month")])[1]'
SELLER_RETAINER_AUGUST = '(//input[contains(@name,"august month")])[1]'
SELLER_RETAINER_SEPTEMBER = '(//input[contains(@name,"september month")])[1]'
SELLER_RETAINER_OCTOBER = '(//input[contains(@name,"october month")])[1]'
SELLER_RETAINER_NOVEMBER = '(//input[contains(@name,"november month")])[1]'
SELLER_RETAINER_DECEMBER = '(//input[contains(@name,"december month")])[1]'
SELLER_FIXED_VALUE = '//div[contains(text(),"Seller")]//following::input[@id="monthly_retainer"][1]'
VENDOR_BILLING_DROPDOWN = '//label[@for="Vendor Billing Report"]//following::div[contains(@class,"react-select")][1]'
SAME_FEE_STRUCTURE_ID = '//input[contains(@id,"step")]'
SAME_FEE_STRUCTURE = '//input[contains(@id,"step")]//parent::label'
SAVE_CHANGES_LOCATOR = 'xpath://button[contains(text(),"Save Changes")]'
DISCARD_CHANGES_LOCATOR = '//button[contains(text(),"Discard Changes")]'
CONTRACT_START_DATE = '//label[contains(text(),"Contract Start Date")]//following::button[1]'
INPUT_CONTRACT_DATE = '//input[@name="date"]'
START_DATE = '//div[@class="react-date-picker__inputGroup"]'
SERVICE_CONTRACT_LENGTH = '//span[contains(text(),"Months")]'
ACTIVE_DATE = '//button[contains(@class,"now")]'
CONTRACT_LENGTH_DROPDOWN = '//label[text()="Contract Length"]//following::div[contains(@class,"react-select")][1]'
OPEN_CONTRACT_LENGTH_DROPDOWN = '//div[contains(@class,"form-control-error__menu")]'
CONTRACT_LENGTH = '//label[text()="Contract Length"]//following::div[contains(text(),"Months")][1]'
AGREEMENT_COMPANY = '//h3[contains(text(),"Service")]//following::div[1]/p[1]//child::span[2]'
AGREEMENT_ADDRESS = '//h3[contains(text(),"Service")]//following::div[1]/p[1]//child::span[3]'
AGREEMENT_CONTRACT_LENGTH = '//span[contains(text(),"Months")]'
AGREEMENT_COMPANY2 = '//p[contains(@class,"BT-ser-agr-company2")]/span'
AGREEMENT_ADDRESS2 = '(//span[contains(text(),"3726")])[2]'
ADDRESS_LOCATOR = '//input[@placeholder="Enter Address"]'
STATE_LOCATOR = '//input[@placeholder="Enter State"]'
CITY_LOCATOR = '//input[@placeholder="Enter City"]'
POSTCODE_LOCATOR = '//input[@placeholder="Enter Postcode"]'
AGREEMENT_START_DATE = '//div[@id="agreement"]//child::div[1]/p[1]/span[1]'
CHANGES_TEXT_LOCATOR = 'xpath://span[contains(@class,"unsave-changes")]'
SERVICE_AGREEMENT_SECTION = '(//ul[contains(@class,"collapse-inner")])[1]'
FEE_STRUCTURE_SECTION = '(//ul[contains(@class,"collapse-inner")])[2]'
PROCEED_TO_NEXT_SECTION = '(//ul[contains(@class,"collapse-inner")])[1]/li/button[text()="Proceed to Next Section"]'
STATEMENT_OF_WORK = '//h4[contains(text(),"Statement of Work")]//parent::div'
STATEMENT_OF_WORK_HEADER = '//h4[text()="Statement of Work"]'
ADDENDUM_HEADER = '//h4[contains(text(),"Addendum")]'
MONTHLY_RETAINER_LOCATOR = '//input[@name="monthly_retainer"]'
STATEMENT_OF_WORK_SECTION = '(//ul[contains(@class,"collapse-inner")])[3]'
PRIMARY_MARKETPLACE_DROPDOWN = '//label[text()="Primary MarketPlace"]//following::div[contains(@class,"react-select")][1]'
OPEN_PRIMARY_MARKETPLACE_DROPDOWN = '//label[text()="Primary MarketPlace"]//following::div[1]/div/div[contains(@class,"react-select__menu")]'
ACCOUNT_TYPE_DROPDOWN = '//label[text()="Account Type"]//following::div[contains(@class,"react-select")][1]'
REVENUE_SHARE_DROPDOWN = '//label[text()="Revenue Share"]//following::div[1]/div/div[contains(@class,"react-select")]'
OPEN_REVENUE_SHARE_DROPDOWN = '//label[text()="Revenue Share"]//following::div[1]/div/div[contains(@class,"react-select__menu")]'
SALES_THRESHOLD_LOCATOR = '//input[@name="sales_threshold"]'
BILLING_CAP_LOCATOR = '//input[@name="billing_cap"]'
COPY_INCREMENT_LOCATOR = '//label[text()="Copy"]//parent::div//following::div[1]/button[@class="increment"]'
COPY_DECREMENT_LOCATOR = '//label[text()="Copy"]//parent::div//following::div[1]/button[@class="decrement"]'
COPY_INPUT = '//label[text()="Copy"]//parent::div//following::div[1]/input'
DESIGN_INPUT = '//label[text()="Design"]//parent::div//following::div[1]/input'
DESIGN_INCREMENT_LOCATOR = '//label[text()="Design"]//parent::div//following::div[1]/button[@class="increment"]'
DESIGN_DECREMENT_LOCATOR = '//label[text()="Design"]//parent::div//following::div[1]/button[@class="decrement"]'

STATEMENT_OF_WORK_SECTION = '//label[text()="Monthly Retainer"]//ancestor::ul'
#CUSTOMER_SUPPORT_LOCATOR = '//label[text()="Customer Support"]'
#CUSTOMER_SUPPORT_LOCATOR_ID = '//label[text()="Customer Support"]/input[@id="TSAgSeI"]'
#LOGISTIC_MANAGEMENT_LOCATOR_ID = '//label[text()="Logistics Management"]/input[@id="TSODQJH"]'
#LOGISTIC_MANAGEMENT_LOCATOR = '//label[text()="Logistics Management"]'
#INVENTORY_RECONCILIATION_ID = '//label[text()="Inventory Reconciliation"]/input[contains(@name,"Inventory")]'
#INVENTORY_RECONCILIATION = '//label[text()="Inventory Reconciliation"]'
MONTHLY_BUDGET = '//input[@placeholder="Enter budget"]'
AGENCY_FEE_DROPDOWN = '//label[contains(text(),"Agency")]//following::div[contains(@class,"react-select")][1]'
INITIAL_PERIOD_DROPDOWN = '//label[contains(text(),"INITIAL")]//following::div[contains(@class,"react-select")][1]'
DSP_MARKETPLACES_DROPDOWN = '//label[text()="DSP Marketplaces"]//following::div[contains(@class,"react-select__indicators")]'
DSP_MARKETPLACES = '//label[@for="dsp_marketplaces"]//following::div[contains(@class,"is-multi")][1]/div'
REMOVE_DSP_MARKETPLACES = '//label[@for="dsp_marketplaces"]//following::div[contains(@class,"remove")][1]'
ADDITIONAL_MARKETPLACES = '//label[text()="Additional Marketplaces"]'
ADDITIONAL_MARKETPLACES_ID = '//label[text()="Additional Marketplaces"]/input[@id="additional_marketplaces"]'
ADDITIONAL_MARKETPLACES1_DROPDOWN = '(//label[@for="Seller"]//following::div[contains(@class,"react-select__indicators")])[1]'
ADDITIONAL_MARKETPLACES2_DROPDOWN = '(//label[@for="Vendor"]//following::div[contains(@class,"react-select__indicators")])[1]'
MARKETPLACES = '//div[contains(@class,"control")][1]//child::div[contains(@class,"label")]'
REMOVE_MARKETPLACE = '//div[contains(@class,"remove")][1]'
OPEN_ADDITIONAL_MARKETPLACES_DROPDOWN = '//div[contains(@class,"react-select__menu")]'
APLUS_CONTENT_ONE_TIME_ID = '//input[@id="TSPllHh"]'
APLUS_CONTENT_ONE_TIME_LABEL = '//input[@id="TSPllHh"]//parent::label'
PRODUCT_INSERT_ONE_TIME_ID = '//input[@id="TSq6Uwq"]'
PRODUCT_INSERT_ONE_TIME_LABEL = '//input[@id="TSq6Uwq"]//parent::label'
AMAZON_BRAND_ONE_TIME_ID = '//input[@id="TSUI0W2"]'
AMAZON_BRAND_ONE_TIME_LABEL = '//input[@id="TSUI0W2"]//parent::label'
LISTING_COPY_ONE_TIME_ID = '//input[@id="TSDrM8x"]'
LISTING_COPY_ONE_TIME_LABEL = '//input[@id="TSDrM8x"]//parent::label'
LISTING_DESIGN_ONE_TIME_ID = '//input[@id="TSqkiR9"]'
LISTING_DESIGN_ONE_TIME_LABEL = '//input[@id="TSqkiR9"]//parent::label'
DOCUMENT_DESIGN_ONE_TIME_ID = '//input[@id="TSPllNM"]'
DOCUMENT_DESIGN_ONE_TIME_LABEL = '//input[@id="TSPllNM"]//parent::label'
LISTING_PHOTOGRAPHY_ID = '//input[@id="TSWyyAE"]'
LISTING_PHOTOGRAPHY_LABEL = '//input[@id="TSWyyAE"]//parent::label'
AMAZON_STOREFRONT_ONE_TIME_ID = '//input[@id="contract-copy-check"]'
AMAZON_STOREFRONT_ONE_TIME_LABEL = '//input[@id="contract-copy-check"]//parent::label'
APLUS_CONTENT_SELLER_LABEL = '//input[@id="TSgoWsF"]//parent::label'
APLUS_CONTENT_SELLER_ID = '//label[text()="A+ Content"]/input[@id="TSgoWsF"]'
STOREFRONT_SUPPORT_SELLER_LABEL = '//input[@id="TSWwsFw"]//parent::label'
STOREFRONT_SUPPORT_SELLER_ID = '//label[text()="Storefront Support"]/input[@id="TSWwsFw"]'
CUSTOMER_SUPPORT_SELLER_ID = '//input[@id="TSzwll6"]'
CUSTOMER_SUPPORT_SELLER_LABEL = '//input[@id="TSzwll6"]//parent::label'
LOGISTIC_MANAGEMENT_SELLER_ID = '//input[@id="TSOq9dE"]'
LOGISTIC_MANAGEMENT_SELLER_LABEL = '//input[@id="TSOq9dE"]//parent::label'
INVENTORY_RECONCILIATION_SELLER_ID = '//input[@id="TSDHyZy"]'
INVENTORY_RECONCILIATION_SELLER_LABEL = '//input[@id="TSDHyZy"]//parent::label'
DSP_ADVERTISE_SELLER_ID = '//input[@id="TSZ6ooN"]'
DSP_ADVERTISE_SELLER_LABEL = '//input[@id="TSZ6ooN"]//parent::label'
ADDITIONAL_MARKETPLACES_SELLER_ID = '//input[@id="Seller"]'
ADDITIONAL_MARKETPLACES_SELLER_LABEL = '//input[@id="Seller"]//parent::label'
APLUS_CONTENT_VENDOR_ID = '//input[@id="TSGK2oQ"]'
APLUS_CONTENT_VENDOR_LABEL = '//input[@id="TSGK2oQ"]//parent::label'
STOREFRONT_SUPPORT_VENDOR_ID = '//input[@id="TSeZnpO"]'
STOREFRONT_SUPPORT_VENDOR_LABEL = '//input[@id="TSeZnpO"]//parent::label'
CUSTOMER_SUPPORT_VENDOR_ID = '//input[@id="TSaEXYd"]'
CUSTOMER_SUPPORT_VENDOR_LABEL = '//input[@id="TSaEXYd"]//parent::label'
LOGISTIC_MANAGEMENT_VENDOR_ID = '//input[@id="TSMYQfE"]'
LOGISTIC_MANAGEMENT_VENDOR_LABEL = '//input[@id="TSMYQfE"]//parent::label'
INVENTORY_RECONCILIATION_VENDOR_ID = '//input[@id="TSggxpL"]'
INVENTORY_RECONCILIATION_VENDOR_LABEL = '//input[@id="TSggxpL"]//parent::label'
DSP_ADVERTISING_VENDOR_LABEL = '(//label[text()="DSP Advertising"])[2]'
DSP_ADVERTISING_VENDOR_ID = '//input[contains(@id,"TSENYuB")]'
ADDITIONAL_MARKETPLACES_VENDOR_ID = '//input[@id="Vendor"]'
ADDITIONAL_MARKETPLACES_VENDOR_LABEL = '//input[@id="Vendor"]//parent::label'
AMAZON_BRAND_STYLE_GUIDE = '//label[text()="Amazon Brand Style Guide"]'
AMAZON_BRAND_STYLE_GUIDE_ID = '//label[text()="Amazon Brand Style Guide"]/input[@id="TSjfNJN"]'
ADDITIONAL_INFOGRAPHICS = '//label[text()="Additional Infographics"]'
ADDITIONAL_INFOGRAPHICS_ID = '//label[text()="Additional Infographics"]/input[@id="TSG6hjI"]'
ADDITIONAL_LISTING_COPY = '//label[text()="Additional Listing Copy"]'
ADDITIONAL_LISTING_COPY_ID = '//label[text()="Additional Listing Copy"]/input[@id="TSXuZ7J"]'
AMAZON_STORE = '//label[text()="Amazon Store"]'
AMAZON_STORE_ID = '//label[text()="Amazon Store"]/input[@id="contract-copy-check"]'
A_PLUS_CONTENT_INCREMENT = '//input[@name="A+ Content"]//parent::div/button[@class="increment"]'
A_PLUS_CONTENT_DECREMENT = '//input[@name="A+ Content"]//parent::div/button[@class="decrement"]'
A_PLUS_CONTENT_INPUT = '//label[text()="A+ Content"]//parent::div//following::div[1]/input'
PRODUCT_INSERTS_INCREMENT = '//input[@name="Product Inserts"]//parent::div/button[@class="increment"]'
PRODUCT_INSERTS_DECREMENT = '//input[@name="Product Inserts"]//parent::div/button[@class="decrement"]'
PRODUCT_INSERTS_INPUT = '//label[text()="Product Inserts"]//parent::div//following::div[1]/input'
AMAZON_BRAND_INCREMENT = '//input[@name="Amazon Brand Style Guide"]//parent::div/button[@class="increment"]'
AMAZON_BRAND_DECREMENT = '//input[@name="Amazon Brand Style Guide"]//parent::div/button[@class="decrement"]'
AMAZON_BRAND_INPUT = '//label[text()="Amazon Brand Style Guide"]//parent::div//following::div[1]/input'
ADDITIONAL_INFOGRAPHICS_INCREMENT = '//input[@name="Additional Infographics"]//parent::div/button[@class="increment"]'
ADDITIONAL_INFOGRAPHICS_DECREMENT = '//input[@name="Additional Infographics"]//parent::div/button[@class="decrement"]'
ADDITIONAL_INFOGRAPHICS_INPUT = '//label[text()="Additional Infographics"]//parent::div//following::div[1]/input'
ADDITIONAL_LISTING_COPY_INCREMENT = '//input[@name="Additional Listing Copy"]//parent::div/button[@class="increment"]'
ADDITIONAL_LISTING_COPY_DECREMENT = '//input[@name="Additional Listing Copy"]//parent::div/button[@class="decrement"]'
ADDITIONAL_LISTING_COPY_INPUT = '//label[text()="Additional Listing Copy"]//parent::div//following::div[1]/input'
AMAZON_STORE_INCREMENT = '//input[@name="amazon service"]//parent::div/button[@class="increment"]'
AMAZON_STORE_DECREMENT = '//input[@name="amazon service"]//parent::div/button[@class="decrement"]'
AMAZON_STORE_INPUT = '//label[text()="Amazon Store"]//parent::div//following::div[1]/input'
PROCEED_TO_NEXT_SECTION2 = '(//ul[contains(@class,"collapse-inner")])[2]/li/button[text()="Proceed to Next Section"]'
AMAZON_STORE_DROPDOWN = '//label[text()="Amazon Store"]//following::div[contains(@class,"indicator")][1]'
AMAZON_STORE_OPEN = '//label[text()="Amazon Store"]//following::div[contains(@class,"menu")]'
DSP_ADVERTISING_HEADER = '//h4[contains(text(),"DSP Advertising")]'
MONTHLY_AD_BUDGET = '//input[@placeholder="Enter budget"]'
DSP_ADVERTISING_SECTION = '//label[text()="Monthly Ad Budget"]//ancestor::ul'
INITIAL_PERIOD_LABEL = '//label[contains(text(),"INITIAL PERIOD")]'
INITIAL_PERIOD_DROPDOWN = '//label[contains(text(),"INITIAL PERIOD")]//following::div[contains(@class,"react-select")][1]'
PROCEED_TO_NEXT_SECTION3 = '(//ul[contains(@class,"collapse-inner")])[3]/li/button[text()="Proceed to Next Section"]'
ADDENDUM = '//h4[contains(text(),"Addendum")]//parent::div'
CHECK_ADDENDUM = '//label[contains(text(),"Addendum")]//parent::div'
ADDENDUM_ID = '//input[@id="add-addendum"]'
CREATE_ADDENDUM =  '//button[text()="Create Addendum"]'
ADDENDUM_EDITOR = '//div[contains(@class,"DraftEditor-root")]'
SAVE_ADDENDUM = '//button[text()="Save Addendum"]'
EDIT_ADDENDUM = '//button[text()="Edit Addendum"]'
DASHBOARD_TAB = '//div[contains(text(),"Dashboard")]'

# CUSTOMER SETUP JOURNEY
AVATAR_PROFILE = '//div[contains(@class,"avatarName")]'
STEP1_HEADER = '//h3[contains(text(),"Digital Presence")]'
STEP2_HEADER = '//h3[contains(text(),"Billing")]'
STEP3_HEADER = '//h3[contains(text(),"Account")]'
DIGITAL_ASK_SOMEONE_CHECKBOX = '//input[@id="digital presence"]'
DIGITAL_ASK_SOMEONE = '//input[@id="digital presence"]//parent::label'
INPUT_ASSIGN = '//label[text()="Assign to (email)"]//input'
SEND_EMAIL_BUTTON = '//button[text()="Send Email"]'
ERROR_EMAIL = '//div[contains(text(),"email address")]'
FACEBOOK = '//input[@name="facebook"]'
TWITTER = '//input[@name="twitter"]'
LINKEDIN = '//input[@name="linkedin"]'
INSTAGRAM = '//input[@name="instagram"]'
PINTEREST = '//input[@name="pinterest"]'
FACEBOOK_DELETE = '//input[@name="facebook"]//parent::div/img'
TWITTER_DELETE = '//input[@name="twitter"]//parent::div/img'
LINKEDIN_DELETE = '//input[@name="linkedin"]//parent::div/img'
INSTAGRAM_DELETE = '//input[@name="instagram"]//parent::div/img'
PINTEREST_DELETE = '//input[@name="pinterest"]//parent::div/img'
FACEBOOK_ERROR = '//input[@name="facebook"]//following::div[contains(text(),"valid URL")]'
BILLING_INFORMATION = '//h3[contains(text(),"Billing")]'
AMAZON_ACCOUNT = '//h3[contains(text(),"Amazon Account")]'
# ACCOUNT_SUMMARY = '//h3[contains(text(),"Account Summary")]'
BACK_STEP = '//div[@class="back-link"]/img'
WEBSITE = '//input[@name="website"]'
WEBSITE_ERROR = '//label[text()="Website"]//following::div[contains(text(),"valid URL")]'
BILLING_ASK_SOMEONE = '//input[@id="billing information"]'
BILLING_ASK_LABEL = '//input[@id="billing information"]//parent::label'
BILLING_PAGE = '//div[contains(@class,"white-card-base")]'
BILLING_CHECKBOX = '//input[@id="contract-copy-check"]'
BIILING_CHECKBOX_LABEL = '//input[@id="contract-copy-check"]//parent::label'
#BILLING_CARDHOLDER = '//input[contains(@placeholder,"Cardholder Name")]'
#BILLING_CREDIT_CARD = '//input[contains(@placeholder,"Credit Card")]'
#BILLING_EXPIRATION = '//input[contains(@placeholder,"Expiration")]'
#BILLING_CVV = '//input[contains(@placeholder,"Enter CVV")]'
BILLING_ADDRESS = '//input[contains(@placeholder,"Address")]'
BILLING_CITY = '//input[contains(@placeholder,"City")]'
BILLING_STATE = '//input[contains(@placeholder,"State")]'
BILLING_POSTCODE = '//input[contains(@placeholder,"Postal Code")]'
BILLING_FIRST_NAME = '//input[contains(@placeholder,"First name")]'
BILLING_LAST_NAME = '//input[contains(@placeholder,"Last name")]'
BILLING_EMAIL = '//input[contains(@placeholder,"Email")]'
BILLING_PHONE = '//input[contains(@placeholder,"Phone")]'
DSP_SIGNOFF_CHECKBOX = '//input[@id="same as billing"]'
DSP_SIGNOFF_LABEL = '//input[@id="same as billing"]//parent::label'
DSP_FIRST_NAME = '//input[@id="same as billing"]//following::input[@placeholder="Enter First name"]'
DSP_LAST_NAME = '//input[@id="same as billing"]//following::input[@placeholder="Enter Last name"]'
DSP_EMAIL = '//input[@id="same as billing"]//following::input[@placeholder="Enter Email"]'
DSP_PHONE_NUMBER = '//input[@id="same as billing"]//following::input[@placeholder="Enter Phone number"]'
STEP_HEADER = '//p[contains(@class,"account-steps")]'
MERCHANT_ASK_SOMEONE = '//input[@id="merchant id"]'
MERCHANT_ASK_SOMEONE_LABEL = '//input[@id="merchant id"]//parent::label'
NO_AMAZON_ACCOUNT_ID = '//input[@id="no_amazon_account"]'
NO_AMAZON_ACCOUNT_LABEL = '//input[@id="no_amazon_account"]//parent::label'
SELLER_CENTRAL_DERAILS = '//p[contains(text(),"Seller Central Details")]'
VENDOR_CENTRAL_DETAILS = '//p[contains(text(),"Vendor Central Details")]'
SELLER_CHECKBOX_ID = '//input[@id="Seller"]'
SELLER_CHECKBOX_LABEL = '//input[@id="Seller"]//parent::label'
SELLER_CENTRAL_INPUT = '//input[contains(@placeholder,"Seller Central")]'
MERCHANT_ID = '//input[contains(@placeholder,"Merchant ID")]'
VENDOR_CHECKBOX_ID = '//input[@id="Vendor"]'
VENDOR_CHECKBOX_LABEL = '//input[@id="Vendor"]//parent::label'
SELLER_ACCOUNT_NAME = '//input[contains(@placeholder,"Enter Seller")]'
MERCHANT_ID = '//input[contains(@placeholder,"Merchant ID")]'
SELLER_ADVERTISER = '//input[contains(@placeholder,"Merchant ID")]//following::input[contains(@placeholder,"Advertiser Name")][1]'
SELLER_AD_ID = '//input[contains(@placeholder,"Merchant ID")]//following::input[contains(@placeholder,"Advertiser ID")][1]'
FIRST_MARKETPLACE = '//h6[contains(@class,"small-title")][1]'
MARKETPLACES_AD_NAME = '//fieldset/div/h6//following::input[contains(@placeholder,"Advertiser Name")]'
MARKETPLACES_AD_ID = '//fieldset/div/h6//following::input[contains(@placeholder,"Advertiser ID")]'
SINGLE_MARKETPLACE_NAME = '//fieldset/h6//following::div/label/input[contains(@placeholder,"Advertiser Name")]'
SINGLE_MARKETPLACE_ID = '//fieldset/h6//following::div/label/input[contains(@placeholder,"Advertiser ID")]'
SELLER_MARKETPLACES = '//label[@for="Seller"]//following::div[contains(@class,"is-multi")][1]/div'
VENDOR_MARKETPLACES = '//label[@for="Vendor"]//following::div[contains(@class,"is-multi")][1]/div'
REMOVE_VENDOR_MARKETPLACES = '//label[@for="Vendor"]//following::div[contains(@class,"remove")][1]'
ADVERTISER_DETAILS = '//ul[contains(@class,"amazon-merchant")]//following::input[@placeholder="Enter Advertiser Name"][1]'

VENDOR_ACCOUNT_NAME = '//input[contains(@placeholder,"Enter Vendor Central")]'
VENDOR_CODE = '//input[contains(@placeholder,"Enter Vendor Code")]'
VENDOR_ADVERTISER = '//input[contains(@placeholder,"Code")]//following::input[contains(@placeholder,"Advertiser Name")][1]'
VENDOR_AD_ID = '//input[contains(@placeholder,"Code")]//following::input[contains(@placeholder,"Advertiser ID")][1]'
ACCOUNT_SUMMARY = '//h3[text()="Account Summary"]'
STEP1 = '//div[contains(text(),"Create Your Account")]/div[@class="completed-status"]'
STEP2 = '//div[contains(text(),"Digital Presence")]/div[@class="completed-status"]'
STEP3 = '//div[contains(text(),"Billing Information")]/div[@class="completed-status"]'
STEP4 = '//div[contains(text(),"Amazon")]/div[@class="completed-status"]'
STEP1_VIEW = '//div[contains(text(),"Digital")]//child::div[contains(@class,"view-details")]'
STEP2_VIEW = '//div[contains(text(),"Billing")]//child::div[contains(@class,"view-details")]'
STEP3_VIEW = '//div[contains(text(),"Account")]//child::div[contains(@class,"view-details")]'
SUBMIT_SUMMARY = '//button[text()="Submit"]'
RECENT_ACTIVITY = '//p[contains(text(),"Recent Activity")]'
# UPLOAD BRAND ASSETS
ACTIVE_AGREEMENT_LENGTH = '//p[contains(text(),"Active Agreement")]'
BODY = '//body'
ACTIVE_TABLE_ROW = '//table/tbody/tr[position()>1]'
SIGN_TABLE_ROW = '//table/tbody/tr[position()>1]/td[2]/div[@class="sign-box"]'
UPLOAD_ASSETS_BUTTON = '//button[text()="Upload Assets"]'
SELECT_ACCOUNT_HEADER = '//h2[text()="Select Account"]'
SELECT_DROPDOWN = '//div[text()="Select..."]'
OPEN_SELECT_DROPDOWN = '//div[contains(@class,"menu")]'
HEADER= '//div/h2'
UPLOAD_BRAND_ASSETS_CONTINUE = '//button[text()="Continue"]'
BROWSE = '//input[@type="file"]'
BRAND_LOGO_HEADER = '//h3[text()="Brand Logo"]'
FILE_COUNT_FOR_BRAND_STEPS = '//ul[@class="asset-check-list"]/li/div/div[2][contains(text(),"files uploaded")]'
BRAND_LOGO_IMAGE_LIST = '//ul[@class="Image-container"]/li'
BRAND_LOGO_FILE_UPLOAD_COUNT = '//div[text()="Brand Logo"]//following::div[contains(text(),"uploaded")][1]'
FIRST_IMAGE = '//ul[@class="Image-container"]/li[1]/div'
DELETE_IMAGE = '//div[@class="remove-box"]'
DELETE_CONFIRM_BUTTON = '//div[@class="delete-msg"]'
DELETE_BY_MODAL = '//span[text()="Delete"]//parent::li'
YES_BUTTON = '//button[text()="Yes"]'
CLOSE_ICON = '//img[contains(@class,"remove-cross-icon")]//parent::li'
NEXT_STEP = '//button[contains(text(),"Next Step")]'
BRAND_GUIDELINES = '//h3[text()="Brand Guidelines"]'
BRAND_GUIDELINES_FILE_UPLOAD_COUNT = '//div[text()="Brand Guidelines"]//following::div[contains(text(),"uploaded")][1]'
BRAND_ASSETS_TAB = '//div[contains(text(),"Brand Assets")]'
ERROR_MESSAGE = '//div[contains(text(),"Please upload file that")]'
FONT_FILES = '//h3[text()="Font Files"]'
Font_FilES_FILE_UPLOAD_COUNT = '//div[text()="Font Files"]//following::div[contains(text(),"uploaded")][1]'
NONE_AVAILABlE = 'xpath://label[contains(@class,"customer-pannel")]'
STEPS_COMPLETED =   '//label[contains(text(),"Upload Brand Assets")]/div[contains(@class,"steps")]'
BRAND_ASSETS_TAB = '//div[contains(text(),"Brand Assets")]//parent::li'
DOWNLOAD_ASSETS = '//li[text()="Download"]'
DOWNLOAD_SELECTED = '//span[contains(text(),"files selected")]'
DOWNLOAD_SELECTED_BUTTON = '//button[contains(text(),"Download Selected")]'
CANCEL_BUTTON = '//button[contains(text(),"Cancel")]'
BRAND_GUIDELINES_TAB = '//div[text()="Brand Guidelines"]'
ASSET_DROPDOWN = '//div[contains(@class,"react-select")]'
OPEN_ASSET_DROPDOWN = '//div[contains(@class,"__menu")]'

# Dashboard
DASHBOARD_TITLE = '//p[contains(@class,"black-heading-title")]'
MY_PARTNER_DROPDOWN = '//div[text()="My Partners"]'
OPEN_MY_PARTNER_DROPDOWN = '//div[contains(@class,"react-select__menu")]'
SPONSERED_AD_PARTNER = '//div[text()="Sponsored Ad Partners"]'
OPEN_SPONSERED_AD_PARTNER = '//div[text()="Sponsored Ad Partners"]//following::div[contains(@class,"react-select__menu")]'
SEARCH_LOCATOR = '//input[@placeholder="Search"]'
COMPANY_RECORD = '//tbody/tr[1]/td[1]'
SALES_PERFORMANCE_TAB = '//li[contains(text(),"Sales Performance")]'
SALES_PERFORMANCE_TEXT = '//p[contains(text(),"Sales Performance")]'
SALES_PERFORMANCE_DROPDOWN = '//p[contains(text(),"Sales Performance")]//following::div[contains(@class,"react-select")][1]'
DAILY = '//label[text()="Daily"]//parent::li'
WEEKLY = '//label[text()="Weekly"]//parent::li'
MONTHLY = '//label[text()="Monthly"]//parent::li'
RECENT = '//span[text()="Recent"]'
PREVIOUS = '//span[text()="Previous"]'
REVENUE = '//div[contains(text(),"REVENUE")]'
REVENUE_STATUS = '//div[contains(text(),"REVENUE")]//parent::div[contains(@class,"order")]'
UNITS_SOLD = '//div[contains(text(),"UNITS SOLD")]'
UNITS_SOLD_STATUS = '//div[contains(text(),"UNITS")]//parent::div[contains(@class,"order")]'
TRAFFIC = '//div[contains(text(),"TRAFFIC")]'
CONVERSION = '//div[contains(text(),"CONVERSION")]'
REVENUE_UP = '//div[contains(text(),"REVENUE")]//following::div[1]/span'
REVENUE_DOWN = '//div[contains(text(),"REVENUE")]//following::div[contains(@class,"vs")][1]'
REVENUE_PERCENTAGE = '//div[contains(text(),"REVENUE")]//following::div[contains(@class,"perentage")][1]'
UNITS_SOLD_UP = '//div[contains(text(),"UNITS")]//following::div[1]/span'
UNIT_SOLD_DOWN = '//div[contains(text(),"UNITS")]//following::div[contains(@class,"vs")][1]'
UNIT_PERCENTAGE = '//div[contains(text(),"UNITS")]//following::div[contains(@class,"perentage")][1]'
TRAFFICE_UP = '//div[contains(text(),"TRAFFIC")]//following::div[1]/span'
TRAFFIC_DOWN = '//div[contains(text(),"TRAFFIC")]//following::div[contains(@class,"vs")][1]'
TRAFFIC_PRECENTAGE = '//div[contains(text(),"TRAFFIC")]//following::div[contains(@class,"perentage")][1]'
CONVERSION_UP = '//div[contains(text(),"CONVERSION")]//following::div[@class="number-rate"]'
CONVERSION_DOWN = '//div[contains(text(),"CONVERSION")]//following::div[@class="vs"]'
CONVERSION_PERCENTAGE = '//div[contains(text(),"CONVERSION")]//following::div[contains(@class,"perentage")][1]'
INVENTORY_SCORE = '//p[text()="Inventory Score (IPI)"]'
AD_PERFORMANCE = '//li[text()="Ad Performance"]'
PREVIOUS_ARROW = '//button[contains(@class,"prevButton")]'
SELECT_DATE = '//span[text()="1"]//ancestor::button[1]'
NEXT_ARROW = '//button[contains(@class,"NextButton")]'
APPLY_BUTTON = '//button[text()="Apply"]'
ADD_SALES = '//div[contains(text(),"Ad Sales")]'
ADD_SALES_BOX = '//div[contains(@id,"adsalescard")]//parent::div[contains(@class,"order")]'
ADD_SPEND_BOX = '//div[contains(@id,"adspendcard")]//parent::div[contains(@class,"order")]'
ADD_CONVERSION_BOX = '//div[contains(@id,"adconversion")]//parent::div[contains(@class,"order")]'
IMPRESSION_BOX = '//div[contains(@id,"sponsored-impression")]//parent::div[contains(@class,"order")]'
ACOS_BOX = '//div[contains(@id,"Acoscard")]//parent::div[contains(@class,"order")]'
ROAS_BOX = '//div[contains(@id,"Roascard")]//parent::div[contains(@class,"order")]'
CLICKS_BOX = '//div[contains(@id,"clickcard")]//parent::div[contains(@class,"order")]'
CLICK_THROUGH_RATE_BOX = '//div[contains(@id,"clickrate")]//parent::div[contains(@class,"order")]'
AD_PERFORMANCE_DROPDOWN = '//div[@id="BT-adperformancedata-daysfilter"]//child::div[contains(@class,"days-performance")]'
SPONSERED_AD_PARTNER_DAILY = '//li[contains(@id,"BT-adperformance-days")]//child::input'
DSP_IMPRESSION_CARD = '//div[contains(@id,"dspad-impressioncard")]//parent::div[contains(@class,"order")]'
DSP_SPEND_CARD = '//div[contains(@id,"dspad-dspspendcard")]//parent::div[contains(@class,"order")]'
DSP_TOTAL_PRODUCT_CARD = '//div[contains(@id,"dspad-totalproductcard")]//parent::div[contains(@class,"order")]'
DSP_TOTAL_ROAS_CARD = '//div[contains(@id,"dspad-totalroascard")]//parent::div[contains(@class,"order")]'
DSP_TOTAL_DPVR_CARD = '//div[contains(@id,"dspad-totaldpvrcard")]//parent::div[contains(@class,"order")]'
DSP_TTL_BRAND_CARD = '//div[contains(@id,"dspad-TTLBrandcard")]//parent::div[contains(@class,"order")]'
DSP_PRODUCT_SALES_CARD = '//div[contains(@id,"dspad-productsalescard")]//parent::div[contains(@class,"order")]'
DSP_ROAS_CARD = '//div[contains(@id,"dspad-roascard")]//parent::div[contains(@class,"order")]'

### Notes #####
CUSTOMER_DASHBOARD = '//div[contains(@class,"customer-list-header-sticky")]'
BRAND_NAME = '//div[contains(@class,"brand-name")]'
BACK_TO_CUSTOMER = '//div[contains(@class,"back-btn-link")]'
NOTES_MODAL = '//div[contains(@class,"header-title")]'
ACTIVITY_MENU = '//div[contains(text(),"Activity")]'
ADD_NOTES = '//span[contains(text(),"Add note")]//parent::li'
NOTES_BUTTON = '//button[contains(@class,"notes-btn")]'
TEXT_NOTES = '//div[contains(@class,"DraftEditor-root")]'
ADD_NOTES_BUTTON = '//button[contains(text(),"Add Note")]'
FIRST_NOTE = '//div[@class="notes-pin-unpin"][1]//span[@class="cursor"]/span[@class="note-text"]'
DELETE_NOTE = '//div[@class="notes-pin-unpin"][1]//child::span[@class="delete"]'
DELETE_NOTE_CONFIRM = '//div[@class="notes-pin-unpin"][1]//child::span[@class="delete"]/div[@class="delete-msg"]'
CLOSE_NOTES = '//img[contains(@class,"remove")]//parent::li'
ACTIVITY_DELETE_NOTE = '//p[contains(text(),"Recent Activity")]//following::div[contains(@class,"activity")][1]//span/p'
MODAL_ADD_NOTE = '//ul[@class="contract-download-nav"]/li[1]'
NOTE_MODAL = '//div[@id="editor"]'
LIST_OF_ACTION = '//div[@id="editor"]//child::div[@class="notes-pin-unpin"][1]//child::ul[@class="more-action"]/li'
LAST_NOTE_TIMESTAMP = '//div[@id="editor"]/div[@class="notes-pin-unpin"][last()]//child::div[contains(@class,"time-date")]'
PIN_LAST_NOTE = '//div[@id="editor"]/div[@class="notes-pin-unpin"][last()]//child::ul/li[last()]'
UNPIN_NOTE = '//div[@id="editor"]//child::div[@class="notes-pin-unpin"][1][last()]//child::ul[@class="more-action"]/li[last()]'
FIRST_EDIT = '//div[@id="editor"]//child::div[@class="notes-pin-unpin"][1][last()]//child::ul/li[1]'
EDIT_TEXT = '//div[@class="DraftEditor-editorContainer"]'
SAVE_BUTTON = '//button[contains(text(),"Save")]'
FIRST_TIMESTAMP = '//div[@id="editor"]/div[@class="notes-pin-unpin"][1]//child::div[contains(@class,"time-date")]'
ROW_DATA = '//div[@id="editor"]//child::div//child::span[@class="pin"]/ul/li[1]'
USER_NOTE = '//div[@id="editor"]//child::div[@class="notes-pin-unpin"]//child::span[@class="font-bold"]'
SEARCH_NOTE = '//input[@placeholder="Search"]'
ALL_FILTER_NOTE = '//div[@class="dropdown-select-all-notes"]'
ARCHIVE_NOTE = '//div[@id="editor"]//child::div[@class="notes-pin-unpin"][1]//child::ul/li[2]'
ARCHIVE_MESSAGE = '//div[contains(text(),"Note Archived")]'
ALL_NOTES = '//label[text()="All Notes"]//parent::div'
MY_NOTES = '//label[text()="My Notes"]//parent::div'
TEAM_NOTES = '//label[text()="Team Notes"]//parent::div'
TEAM_NOTES_OPTION = '//ul[@class="notes-option"]//child::li[@class="checkbox-option"]'
TEAM_NOTE_LABEL = '//ul[@class="notes-option"]//child::li/div/label[contains(@class,"customer-pannel")]'
UNARCHIVE_NOTES = '//div[contains(@class,"commemt")]//child::ul[@class="more-action"]/li[2]'
UNARCHIVE_BUTTON = '//label[text()="Only show archived"]//parent::div'
FIRST_UNARCHIVE = '//div[@id="editor"]//child::div[@class="notes-pin-unpin"][1][last()]//child::ul/li[2]'
HIDE_UNARCHIVE_BUTTON = '//label[text()="Hide archived"]//parent::div'

### CUSTOMER LIST #######
VIEW_DROPDOWN = '//div[@id="BT-view-customerlist-dropdown"]'
REVENUE_HEADER = '//div[contains(@class,"revenue")]'
UNITS_SOLD_HEADER = '//div[contains(@class,"units")]'
TRAFFIC_HEADER = '//div[contains(@class,"traffic")]'
CONVERSION_HEADER = '//div[contains(@class,"conversion")]'
SECOND_COLUMN = '//tbody/tr/td[2]'
THIRD_COLUMN = '//tbody/tr/td[3]'
FOURTH_COLUMN = '//tbody/tr/td[4]'
FIFTH_COLUMN = '//tbody/tr/td[5]'
CUSTOMER_STATS_DROPDOWN = '//div[contains(@id,"BT-stats-customerlist-dropdown")]'
CUSTOMER_SORT_DROPDOWN = '//div[contains(@id,"BT-sort-customerlist-dropdown")]'
BGS_FILTER = '//div[@id="BT-user-customerlist-dropdown"]'
BGS_NAME = '//tbody/tr/td[1]/div[@class="user-name"]'
CUSTOMER_STATUS_LIST = '//div[text()="Customer Status"]//following::ul[1]/li'
ACTIVE_STATUS = '//label[text()="Active"]//parent::div'
STATUS_LIST = '//tbody/tr/td[3]/div[@class="status"]'
ACTIVE_CHECKBOX = '//label[text()="Active"]/input[@id="active"]'
PENDING_ACOUNT_STATUS = '//label[text()="Pending Account Setup"]//parent::div'
PENDING_ACOUNT_CHECKBOX = '//label[text()="Pending Account Setup"]/input[@id="pending account setup"]'
AT_RISK_STATUS = '//label[text()="At Risk"]//parent::div'
AT_RISK_CHECKBOX = '//label[text()="At Risk"]/input[@id="at risk"]'
PENDING_CANCELLATION_STATUS = '//label[text()="Pending Cancellation"]//parent::div'
PENDING_CANCELLATION_CHECKBOX = '//label[text()="Pending Cancellation"]/input[@id="pending cancellation"]'
INACTIVE_STATUS = '//label[text()="Inactive"]//parent::div'
INACTIVE_CHECKBOX = '//label[text()="Inactive"]/input[@id="inactive"]'
ACCOUNT_TYPE_LIST = '//tbody/tr/td[2]/div[@class="status"]'
VENDOR_STATUS = '//label[text()="Vendor"]//parent::div'
VENDOR_CHECKBOX = '//label[text()="Vendor"]/input[@id="Vendor"]'
SELLER_STATUS = '//label[text()="Seller"]//parent::div'
SELLER_CHECKBOX = '//label[text()="Seller"]/input[@id="Seller"]'
HYBRID_STATUS = '//label[text()="Hybrid"]//parent::div'
HYBRID_CHECKBOX = '//label[text()="Hybrid"]/input[@id="Hybrid"]'
ACCOUNT_TYPE_STATUS_LIST = '//div[text()="Account Type"]//following::ul[contains(@class,"check-box")][1]/li'
CONTRACT_STATUS_LIST = '//div[text()="Contract Status"]//following::ul[contains(@class,"check-box")][1]/li'
CONTRACT_TYPE_LIST = '//div[text()="Contract Type"]//following::ul[contains(@class,"check-box")][1]/li'
RECURRING_STATUS = '//label[text()="Recurring"]'
ONE_TIME_STATUS = '//label[text()="One Time"]'
DSP_ONLY_STATUS = '//label[text()="DSP Only"]'
RECURRING_90_DAY = '//label[text()="Recurring (90 day notice)"]'
FILTER = '//div[text()="Filters"]'
RESET_FILTERS = '//div[text()="Reset filters"]'
NO_RECORD_FOUND = '//div[contains(@class,"no-record-found")]/img'

########## AMAZON NAME & ID  ##########

STATUS_TEXT = '//span[@class="status_text"]'
AMAZON_ID_EDIT = '//p[contains(text(),"Amazon")]//following::div[@class="edit-details"]'
COMPANY_DETAILS = '//div[text()="Company Details"]'
SELLER_NAME = '//input[contains(@placeholder,"Seller")]'
MERCHANT_ERROR = '//div[contains(text(),"Special")]'
ADVERTISER_NAME = '//div[@id="advertiser_name"][1]/div/label/input[@placeholder="Advertiser Name"]'
ADVERTISER_ID = '//div[@id="advertiser_id"][1]/div/label/input[contains(@placeholder,"Advertiser")]'
VENDOR_NAME = '//input[contains(@placeholder,"Vendor")]'
CONFIRM_BUTTON = '//button[text()="Confirm"]'
MODAL = '//div[@class="modal-body"]'
VENDOR_ADVERTISER_NAME = '//div[@id="advertiser_name"][2]/div/label/input[@placeholder="Advertiser Name"]'
VENDOR_ADVERTISE_ID = '//div[@id="advertiser_id"][2]/div/label/input[contains(@placeholder,"Advertiser")]'


############# Reports ###########
NAVIGATION_MODULE = '//ul[@class="tabs scrollable-container "]/li'
REPORT_TABLE = '//table[@class="sc-fFubgz bjNVbG"]' 
REPORT_TYPE = '//table[@class="sc-fFubgz bjNVbG"]/tbody/tr/td/div[2][@class="status"]'
DISABLE_DOWNLOAD = '//table[@class="sc-fFubgz bjNVbG"]/tbody/tr/td[3]'
SEARCH_BOX = '//input[@placeholder="Search"]'
RESET_FILTER = '//p[normalize-space(text())="Reset filters"]'
REPORTTYPE_DROPDOWN = '(//div[@id="BT-ReportDashSearchInput"])[2]'
REPORT_DOWNLOAD = '//img[@alt="download"]'
SELECT_BP = '//div[@id="BT-ReportBPDropdown"]'
TIMEFRAME_FILTER = '//div[@id="BT-ReportBPDropdownTimeFilter"]'
PREVIOUS_ARROW = '//button[@class="rdrNextPrevButton rdrPprevButton"]'
